site_name: allink-core-static
pages:
  - Introduction: 'index.md'
  - Overview:
    - Important notes: 'overview/important.md'
    - How to update: 'overview/update.md'
    - Webpack: 'overview/webpack.md'
    - NPM: 'overview/npm.md'
  - Javascript:
    - General Usage: 'javascript/usage.md'
    - Custom Events: 'javascript/custom-events.md'
    - Libraries: 'javascript/libraries.md'
  - Stylesheets:
    - General Usage: 'stylesheets/usage.md'
    - Bootstrap: 'stylesheets/bootstrap.md'
    - BEM methodology: 'stylesheets/bem.md'
    - Variables: 'stylesheets/variables.md'
    - Grid: 'stylesheets/grid.md'
    - Breakpoints: 'stylesheets/breakpoints.md'
    - Colors: 'stylesheets/colors.md'
    - Text Container: 'stylesheets/text-container.md'
    - Typography: 'stylesheets/typography.md'
    - Form General: 'stylesheets/forms.md'
    - Buttons: 'stylesheets/buttons.md'
    - z-index: 'stylesheets/z-index.md'
  - Plugins:
    - Content Plugin: 'plugins/content-plugin.md'
    - App Content Plugin: 'plugins/app-content-plugin.md'
  - Modules:
    - Modals: 'modules/modals.md'
    - WYSYWIG Editor: 'modules/editor.md'
    - OnScreen (Scroll Spy): 'modules/onscreen.md'
    - Lazyloading: 'modules/lazyloading.md'
  - Templates:
    - Base: 'templates/base.md'
    - Setting up page templates: 'templates/page-templates.md'
    - Setting up app plugin templates: 'templates/plugins.md'
    - App detail view: 'templates/app-detail.md'
    - Image Template Tag: 'templates/image.md'
    - Styleguide: 'templates/styleguide.md'
extra_css:
  - custom.css
markdown_extensions:
  - admonition
theme: readthedocs
